### ISSUE TITLE
Module convert_df_to_geodf not found

### ISSUE THREAD

**Issue by elsadg** [benmack/eo-box#20]
hi @benmack. I am having an issue (I am using eobox version 0.3.1.). Python version 3.6.10.
I can import fine eobox. 

`import convert_df_to_geodf`

**Error**
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-22-bb79235e32c0> in <module>
----> 1 import convert_df_to_geodf

ModuleNotFoundError: No module named 'convert_df_to_geodf'
```

Thank you!

**Comment by benmack** [comment]
Hi @elsadg. 
Thanks for reporting! Could you please check if it now works for you with v0.3.2 ?

**Comment by elsadg** [comment]
Hi @benmack. Works fine now. Thanks a lot! :)
